### ISSUE TITLE
Issue: Bug/Performance Issue [Physical Robot]

### ISSUE THREAD

**Issue by ericwyy** [BerkeleyAutomation/gqcnn#132]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Python version:python3.7
- Installed using pip or ROS: conda
- Camera:SR300
- GPU model (if applicable):GTX1650
When I test my image, 
![Image text](https://github.com/ericwyy/ericwyy/blob/master/1depth_frame_0.png)
![Image text](https://github.com/ericwyy/ericwyy/blob/master/segmask_0.png)
(https://github.com/ericwyy/ericwyy/blob/master/depth_0.npy)
 the following error occurs when I run:
Traceback (most recent call last):
  File "/home/wyy/work_space/grasp/src/gqcnn/examples/policy_9_19.py", line 258, in <module>
    action = policy(state)
  File "/home/wyy/anaconda3/envs/py37/lib/python3.7/site-packages/gqcnn/grasping/policy/policy.py", line 223, in __call__
    return self.action(state)
  File "/home/wyy/anaconda3/envs/py37/lib/python3.7/site-packages/gqcnn/grasping/policy/policy.py", line 400, in action
    action = self._action(state)
  File "/home/wyy/anaconda3/envs/py37/lib/python3.7/site-packages/gqcnn/grasping/policy/policy.py", line 1290, in _action
    grasps, q_values = self.action_set(state)
  File "/home/wyy/anaconda3/envs/py37/lib/python3.7/site-packages/gqcnn/grasping/policy/policy.py", line 1014, in action_set
    raise NoValidGraspsException()
gqcnn.utils.policy_exceptions.NoValidGraspsException
CrossEntropyRobustGraspingPolicy WARNING  No valid grasps could be found
GQCNNTF    INFO     Closing TF Session...

**Comment by yding25** [comment]
Sorry for the irrelevant answer. Is the project still maintained? 
I cannot download the pre-trained model because the link is invalid now.
