### ISSUE TITLE
Suction_policy.py from dev_jeff Branch : KeyError 'vmin'

### ISSUE THREAD

**Issue by SonVad** [BerkeleyAutomation/gqcnn#16]
Hi,
after installing all the dependencies I try to get the suction_policy example running(from dev_jeff branch), but there's this error:

```
python examples/suction_policy.py
WARNING:root:Failed to import geometry msgs in rigid_transformations.py.
WARNING:root:autolab_core not installed as catkin package, RigidTransform ros methods will be unavailable
/usr/local/lib/python2.7/dist-packages/h5py-2.7.1-py2.7-linux-x86_64.egg/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
WARNING:root:Unable to import pylibfreenect2. Python-only Kinect driver may not work properly.
WARNING:root:Unable to import openni2 driver. Python-only Primesense driver may not work properly
WARNING:root:primesense_sensor.py not installed as catkin package. ROS functionality not available.
WARNING:root:Failed to import ROS in phoxi_sensory.py. PhoXiSensor functionality unavailable.
DEBUG:root:Contour 0 area: 1433.500
DEBUG:root:Contour 1 area: 4260.000
DEBUG:root:Contour 2 area: 562.500
DEBUG:root:Contour 3 area: 1490.000
DEBUG:root:Contour 4 area: 3746.500
DEBUG:root:Contour 5 area: 7460.500
DEBUG:root:Sampling 2d candidates
INFO:root:Filtering took 0.034 sec
/home/hans/catkin_ws2/src/perception/perception/image.py:3150: RuntimeWarning: invalid value encountered in divide
  normal_data = pc_grads / np.tile(pc_grad_norms[:, np.newaxis], [1, 3])
/home/hans/catkin_ws2/src/perception/perception/image.py:3224: RuntimeWarning: invalid value encountered in greater
  if np.any((np.abs(np.linalg.norm(data, axis=2) - 1.0) > 1e-4)
INFO:root:Normal cloud took 0.150 sec
INFO:root:Loop took 0.053 sec
DEBUG:root:Sampled 200 grasps from image
DEBUG:root:Sampling grasps took 0.247 sec
INFO:root:Computing the seed set took 0.260 sec
INFO:root:CEM iter 0
/usr/local/lib/python2.7/dist-packages/gqcnn-0.1.0-py2.7.egg/gqcnn/grasp_quality_function.py:132: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
INFO:root:Prediction took 0.105 sec
Traceback (most recent call last):
  File "examples/suction_policy.py", line 181, in <module>
    action = policy(state)
  File "build/bdist.linux-x86_64/egg/gqcnn/policy.py", line 161, in __call__
    state = RgbdImageState(rgbd_im, camera_intr)
  File "build/bdist.linux-x86_64/egg/gqcnn/policy.py", line 555, in action
    
KeyError: 'vmin'
INFO:rospy.core:signal_shutdown [atexit]
```

When running example/policy.py every things works great, any clue whats wrong? ``

**Comment by SonVad** [comment]
Solved the problem:

vmin and vmax was not defined in suction_policy.yaml.
